### ISSUE TITLE
Long resource names overflow container

### ISSUE THREAD

**Issue by mzur** [ArunaStorage/website#71]
Long resource names could be handled with a `text-overflow: ellipsis` CSS rule (and show the full name on hover with the `title` HTML attribute):

![image](https://github.com/ArunaStorage/ArunaWeb/assets/2457311/c1c5cb87-5e2b-4d21-bef9-7a505bb50b33)

**Comment by St4NNi** [comment]
Thanks for reporting and mentioning a possible fix. I will try to group these "visual" issues in an umbrella issue and fix them with the next release.
