### ISSUE TITLE
Search pagination shows 3 pages but the last is empty

### ISSUE THREAD

**Issue by mzur** [ArunaStorage/website#73]
In the search UI, there is a pagination with 3 pages. But the last page is empty:

![image](https://github.com/ArunaStorage/ArunaWeb/assets/2457311/be995a2d-eef5-4617-8f44-14ef70dd034b)

**Comment by St4NNi** [comment]
Thanks for reporting, this is most likely an off-by-one error in the range calculation. I will try to group these "visual" issues in an umbrella issue and fix them with the next release.
